server:
  port: 2022

spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      routes:
        - id: CustomerService
          uri: lb://CustomerService
          predicates:
            - Path=/customer/**
          filters:
            - name: CircuitBreaker
              args:
                name: CustomerService
                fallbackuri: forward:/customerfallback

        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: ProductService
                fallbackuri: forward:/productfallback

        - id: OrderDetailsService
          uri: lb://OrderDetailsService
          predicates:
            - Path=/orderdetails/**
          filters:
            - name: CircuitBreaker
              args:
                name: OrderDetailsService
                fallbackuri: forward:/orderdetailsfallback


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream